# Generated by Django 3.2.7 on 2021-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhapKhoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.TextField(blank=True, default='')),
                ('input_date', models.DateField(blank=True, null=True)),
                ('license_no', models.TextField(blank=True, default='')),
                ('provider', models.TextField(blank=True, default='')),
                ('pn_13', models.TextField(blank=True, default='')),
                ('pn_10', models.TextField(blank=True, default='')),
                ('bosch_no', models.TextField(blank=True, default='')),
                ('z_exel_no', models.TextField(blank=True, default='')),
                ('stamping', models.TextField(blank=True, default='')),
                ('english_des', models.TextField(blank=True, default='')),
                ('import_des', models.TextField(blank=True, default='')),
                ('app_des', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('dap_price', models.FloatField(blank=True, default=0)),
                ('extension_price', models.FloatField(blank=True, default=0)),
                ('tax', models.FloatField(blank=True, default=0)),
                ('gia_von', models.FloatField(blank=True, default=0)),
                ('gia_si', models.FloatField(blank=True, default=0)),
                ('gia_le', models.FloatField(blank=True, default=0)),
                ('gia_goc', models.FloatField(blank=True, default=0)),
                ('tong_gia_goc', models.FloatField(blank=True, default=0)),
                ('ratio', models.FloatField(blank=True, default=0)),
                ('vat_percentage', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='POModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.TextField(blank=True, default='')),
                ('pn_13', models.TextField(blank=True, default='')),
                ('pn_10', models.TextField(blank=True, default='')),
                ('bosch_no', models.TextField(blank=True, default='')),
                ('z_exel_no', models.TextField(blank=True, default='')),
                ('stamping', models.TextField(blank=True, default='')),
                ('country', models.TextField(blank=True, default='')),
                ('english_des', models.TextField(blank=True, default='')),
                ('import_des', models.TextField(blank=True, default='')),
                ('app_des', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('dap_price', models.FloatField(blank=True, default=0)),
                ('extension_price', models.FloatField(blank=True, default=0)),
                ('tax', models.FloatField(blank=True, default=0)),
                ('gia_von', models.FloatField(blank=True, default=0)),
                ('gia_si', models.FloatField(blank=True, default=0)),
                ('gia_le', models.FloatField(blank=True, default=0)),
                ('lead_time', models.TextField(blank=True, default='')),
                ('customer', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XuatKhoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_13', models.TextField(blank=True, default='')),
                ('input_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('gia_goc', models.FloatField(blank=True, default=0)),
                ('tien_goc', models.FloatField(blank=True, default=0)),
                ('english_des', models.TextField(blank=True, default='')),
                ('import_des', models.TextField(blank=True, default='')),
                ('app_des', models.TextField(blank=True, default='')),
                ('customer', models.TextField(blank=True, default='')),
                ('gia_si', models.FloatField(blank=True, default=0)),
                ('gia_le', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XuatNhapTonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ung_dung', models.TextField(blank=True, default='')),
                ('pn_13', models.TextField(blank=True, default='')),
                ('bosch_no', models.TextField(blank=True, default='')),
                ('z_exel_no', models.TextField(blank=True, default='')),
                ('stamping', models.TextField(blank=True, default='')),
                ('english_des', models.TextField(blank=True, default='')),
                ('import_des', models.TextField(blank=True, default='')),
                ('app_des', models.TextField(blank=True, default='')),
                ('dap_price', models.FloatField(blank=True, default=0)),
                ('so_luong_nhap', models.IntegerField(default=0, null=True)),
                ('so_luong_xuat', models.IntegerField(default=0, null=True)),
                ('ton_cuoi', models.IntegerField(default=0, null=True)),
                ('total_po', models.IntegerField(default=0, null=True)),
                ('bor', models.IntegerField(default=0, null=True)),
                ('bor_price', models.FloatField(blank=True, default=0)),
                ('gia_si', models.FloatField(blank=True, default=0)),
                ('gia_le', models.FloatField(blank=True, default=0)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
