# Generated by Django 3.2.7 on 2021-10-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoschRevenueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('major', models.TextField(blank=True, default='')),
                ('client_code', models.TextField(blank=True, default='')),
                ('product_code', models.TextField(blank=True, default='')),
                ('quantity', models.TextField(blank=True, default='')),
                ('price', models.FloatField(blank=True, default=0)),
                ('total', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('major', models.TextField(blank=True, default='')),
                ('client_code', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('value', models.FloatField(blank=True, default=0)),
                ('cost_type', models.TextField()),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SideRevenueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('client_code', models.TextField(blank=True, default='')),
                ('accessory_code', models.TextField(blank=True, default='')),
                ('quantity', models.TextField(blank=True, default='')),
                ('gia_von', models.TextField(blank=True, default='')),
                ('tien_von', models.TextField(blank=True, default='')),
                ('gia_ban', models.TextField(blank=True, default='')),
                ('tien_ban', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
    ]
