# Generated by Django 3.2.7 on 2021-09-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210912_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuatkhomodel',
            name='gia_le',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='xuatkhomodel',
            name='gia_si',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
