# Generated by Django 3.2.7 on 2021-10-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_boschrevenuemodel_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boschrevenuemodel',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='boschrevenuemodel',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='siderevenuemodel',
            name='gia_ban',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='siderevenuemodel',
            name='gia_von',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='siderevenuemodel',
            name='quantity',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siderevenuemodel',
            name='tien_ban',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='siderevenuemodel',
            name='tien_von',
            field=models.FloatField(default=0, null=True),
        ),
    ]
