# Generated by Django 3.2.7 on 2021-10-22 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_congnokhachhangmodel_khachhangmodel_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongNoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat_hang', models.DateField(blank=True, null=True)),
                ('bosch_no', models.TextField(blank=True, default='')),
                ('zexel_no', models.TextField(blank=True, default='')),
                ('ma_tem', models.TextField(blank=True, default='')),
                ('english_name', models.TextField(blank=True, default='')),
                ('vietnamese_name', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('total', models.FloatField(default=0, null=True)),
                ('vat', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PaymentModel',
            new_name='CongNoPaymentModel',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='bosch_no',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='khach_hang',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='ma_tem',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='ngay_xuat_hang',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='total',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='vietnamese_name',
        ),
        migrations.RemoveField(
            model_name='congnokhachhangmodel',
            name='zexel_no',
        ),
        migrations.AddField(
            model_name='congnokhachhangmodel',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='congnokhachhangmodel',
            name='company',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='congnokhachhangmodel',
            name='ma_so_thue',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='congnokhachhangmodel',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='congnokhachhangmodel',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='congnopaymentmodel',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.congnokhachhangmodel'),
        ),
        migrations.DeleteModel(
            name='KhachHangModel',
        ),
        migrations.AddField(
            model_name='congnomodel',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.congnokhachhangmodel'),
        ),
    ]
