# Generated by Django 3.2.7 on 2021-10-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_congnopaymentmodel_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAccessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('customer_rights', 'Global customer rights'), ('vendor_rights', 'Global vendor rights'), ('any_rights', 'Global any rights')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
