# Generated by Django 3.2.7 on 2021-10-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pageaccessmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageaccessmodel',
            options={'default_permissions': (), 'managed': False, 'permissions': (('customer_rights', 'Global customer rights'),)},
        ),
    ]
