# Generated by Django 3.2.7 on 2022-06-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220115_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAccessModel',
        ),
        migrations.AddField(
            model_name='xuatkhomodel',
            name='stamping',
            field=models.TextField(blank=True, default=''),
        ),
    ]
